# **Neural Networks Demystified [Part 1]**

Recommended [Jupyter Theme](https://github.com/dunovank/jupyter-themes) for presenting this notebook:
````
jt -t grade3 -cellw=90% -fs=20 -tfs=20 -ofs=20
````

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


- Here's we'll get a little deeper into the [Neural Networks Demystified](https://www.youtube.com/watch?v=bxe2T-V8XRs) series.
- My hoped for outcome for you here is that you walk away with a fundamental understanding of the basic functioning of neural networks. There's lots of bells and whistles that we'll add later, but this module is just about **the basics**. 
- Really grasping the basics will serve you well when things start to get complex in the **deep learning** module.
- To keep our focuse on the network itself, we'll use really really simple toy data:

![](../graphics/nnd1.png)

- Let's get our data into numpy:

In [11]:
# X = (hours sleeping, hours studying), y = Score on test
X = np.array(([3,5], [5,1], [10,2]), dtype=float)
y = np.array(([75], [82], [93]), dtype=float)

In [12]:
X

array([[ 3.,  5.],
       [ 5.,  1.],
       [10.,  2.]])

In [13]:
y

array([[75.],
       [82.],
       [93.]])

## What are we doing again?
Now, the big idea here, of course, is that we're going to use a neural network to predict your scores on a test based on how many hours you sleep and how many hours you study the night before.

![](../graphics/nnd2.png)

- This is a **supervised regression** problem. 
- What is the difference between supervised and unsupervised machine learning?
- What is the difference between regression and classification problems?

---

![](../graphics/nnd3.png)

- Before we get going, we need to scale our input data
- It's crazy how easy it is to forget to do this, and how **big** of a difference it can make.

In [14]:
X = X/np.amax(X, axis=0)
y = y/100 #Max test score is 100

In [15]:
X

array([[0.3, 1. ],
       [0.5, 0.2],
       [1. , 0.4]])

In [16]:
y

array([[0.75],
       [0.82],
       [0.93]])

## Neural Network Terminology

![](../graphics/nnd4.png)

## Synapses
- Synapses have a reall simple job.

![](../videos/nn_basics.gif)

---

## Neurons

![](../graphics/nnd5.png)

![](../graphics/spacer_small.png)

- Nuerons are responsible for adding up all their inputs and applying an activation function.

![](../graphics/NNQ8-01.png)

---